config/routes.rb
RestaurantReservations::Application.routes.draw do
  resources :reservations, except: :show do
    collection do
      post :check_availability
      post :find
    end
  end

  devise_for :restaurants, controllers: { registrations: "restaurants/registrations" }

  root to: "reservations#new"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant

  self.primary_key = :confirmation_token
  attr_accessible :name, :email, :phone_number, :starts_at, :diner_count

  after_initialize do
    self.starts_at ||= 1.day.from_now.to_datetime.at_beginning_of_hour
    self.diner_count ||= 2
  end

  before_create { generate_token :confirmation_token }

  validates :name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true, length: { in: 7..16 }
  validates :diner_count, numericality: { greater_than: 0 }

  validate :starts_in_future
  validate :ends_after_start
  validate :tables_are_available

  default_scope { order :starts_at }

  def tables_needed
    (self.diner_count.to_f / Restaurant::DINERS_PER_TABLE).ceil
  end

  def starts_at=(starts_at)
    write_attribute :starts_at, starts_at
  end

  def ends_at
    starts_at + restaurant.reservation_length.minutes
  end

  def to_range
    ((starts_at-1.hour)..ends_at)
  end

  def self.expired
    where("starts_at <= ?", 2.hours.ago - Restaurant.first.reservation_length.minutes)
  end

  def self.count_during(range)
    range = range.to_range if range.respond_to?(:to_range)
    t = arel_table
    where(t[:starts_at].in(range)).reduce(0) { |sum, res| sum + res.tables_needed }
  end

  private

  def starts_in_future
    errors.add :starts_at, "must be in future" unless starts_at >= Time.now
  end

  def ends_after_start
    errors.add :ends_at, "must be after start time" unless ends_at > starts_at
  end

  def tables_are_available
    errors.add :starts_at, "not enough available tables for that time" unless restaurant.available_tables_for_span(self) >= tables_needed
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.hex(10)
    end while Reservation.exists?(column => self[column])
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  DINERS_PER_TABLE = 4

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reservations, inverse_of: :restaurant

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :count_tables, :reservation_length

  validates :name, presence: true
  validates :count_tables, presence: true, numericality: { greater_than: 0 }
  validates :reservation_length, presence: true, numericality: { greater_than_or_equal_to: 15 }

  def available_tables_for_span(range)
    count_tables - reservations.count_during(range)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :ensure_restaurant_exists

  def ensure_restaurant_exists
    redirect_to new_restaurant_registration_path unless self.restaurant
  end

  def restaurant
    @restaurant ||= Restaurant.first
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.json
  def index
    authenticate_restaurant!
    @reservations = restaurant.reservations.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = restaurant.reservations.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = restaurant.reservations.new
    @check_time_res = restaurant.reservations.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = restaurant.reservations.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = restaurant.reservations.new(params[:reservation])
    @check_time_res = restaurant.reservations.new

    respond_to do |format|
      if @reservation.save
        ReservationsMailer.confirmation(@reservation).deliver

        format.html { redirect_to root_path, notice: "Your reservation was successfully created. Your confirmation number is #{@reservation.id}" }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = restaurant.reservations.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to root_path, notice: "Reservation updated successfully" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = restaurant.reservations.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  # POST /reservations/check_availability
  def check_availability
    @reservation = restaurant.reservations.new
    @check_time_res = restaurant.reservations.new(params[:reservation])
    @available_tables = restaurant.available_tables_for_span(@check_time_res)

    respond_to do |format|
      format.html { render action: "new" }
    end
  end

  def find
    @reservation = Reservation.find(params[:id])
    redirect_to edit_reservation_path(@reservation)
  end
end

app/controllers/restaurants/registrations_controller.rb
class Restaurants::RegistrationsController < Devise::RegistrationsController
  skip_before_filter :ensure_restaurant_exists, only: [:new, :create]
  before_filter only: [:new] { redirect_to new_restaurant_session_path if Restaurant.any? }
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants/registrations_helper.rb
module Restaurants::RegistrationsHelper
end

app/views/admin/index.html.slim
h2 Upcoming Reservations
- if @reservations
  = render @reservations
- else
  | No upcoming reservations

app/views/layouts/application.html.slim
doctype
html
  head
    title RestaurantReservations
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    - if restaurant_signed_in?
      ul
        li= link_to "Log out", destroy_restaurant_session_path, data: { method: :delete }
        li= link_to "Manage Reservations", reservations_path
        li= link_to "Edit Restaurant Information", edit_restaurant_registration_path
    - flash.each do |name, content|
      div class="flash-#{name}"
        = content
    = yield

app/views/reservations/_availability_form.html.slim
= simple_form_for @check_time_res, url: check_availability_reservations_path do |f|
  = f.input :starts_at, label: "Select a date/time", ampm: true, minute_step: 15
  - if @available_tables
    #{@available_tables} tables are available for #{@check_time_res.starts_at}
  = f.submit "Check Availability"

app/views/reservations/_find_form.html.slim
= form_tag find_reservations_path do |f|
  label for="id" Confirmation Number
  input type="text" name="id"
  input type="submit" value="Search"

app/views/reservations/_form.html.slim
= simple_form_for(@reservation) do |f|
  = f.error_notification

  .form-inputs
    = f.input :starts_at, ampm: true, minute_step: 15
    = f.input :diner_count, label: "Number of Diners"
    = f.input :name
    = f.input :email, as: :email
    = f.input :phone_number

  .form-actions
    = f.button :submit

app/views/reservations/edit.html.slim
h1 Editing reservation

== render 'form'

= link_to 'Back', reservations_path
= link_to 'Cancel Reservation', @reservation, data: { method: :delete }

app/views/reservations/index.html.slim
h1= @restaurant.name

table
  tr
    th Name
    th Email
    th Diners
    th Time
    th
    th
    th

  - @reservations.each do |reservation|
    tr
      td = reservation.name
      td = reservation.email
      td = reservation.diner_count
      td = reservation.starts_at
      td = link_to 'Edit', edit_reservation_path(reservation)
      td = link_to 'Destroy', reservation, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Reservation', new_reservation_path

app/views/reservations/new.html.slim
h1= @restaurant.name

fieldset
  legend
   h2 Check availability
  == render 'availability_form'

h2 Make a Reservation
== render 'form'

h2 Update a Reservation
== render 'find_form'

app/views/reservations/show.html.slim
p#notice = notice

p
  strong Starts at:
  = @reservation.starts_at
p
  strong Ends at:
  = @reservation.ends_at
p
  strong Name:
  = @reservation.name
p
  strong Restaurant:
  = @reservation.restaurant
p
  strong Confirmation token:
  = @reservation.confirmation_token

= link_to 'Edit', edit_reservation_path(@reservation)
'|
= link_to 'Back', reservations_path

app/views/restaurants/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>